name: Build and Use Microservice
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t ml:latest dockerfile/
    - name: Run docker image
      run: docker run -d -p 5000:5000 ml
    - name: Sleep for 10
      run: sleep 10
    - name: G3 = 20 curl request to predict endpoint
      run: curl "http://localhost:5000/predict?school=GP&sex=M&age=16&address=U&famsize=GT3&Pstatus=T&Medu=4&Fedu=3&Mjob=health&Fjob=services&reason=reputation&guardian=mother&traveltime=1&studytime=4&failures=0&schoolsup=no&famsup=no&paid=no&activities=yes&nursery=yes&higher=yes&internet=yes&romantic=no&famrel=4&freetime=2&goout=2&Dalc=1&Walc=1&health=2&absences=4"
    - name: G3 = 19 curl request to predict endpoint
      run: curl "http://localhost:5000/predict?school=GP&sex=M&age=15&address=U&famsize=LE3&Pstatus=A&Medu=4&Fedu=4&Mjob=teacher&Fjob=teacher&reason=course&guardian=mother&traveltime=1&studytime=1&failures=0&schoolsup=no&famsup=no&paid=no&activities=yes&nursery=yes&higher=yes&internet=yes&romantic=no&famrel=5&freetime=5&goout=3&Dalc=1&Walc=1&health=4&absences=6"
    - name: G3 = 0 curl request to predict endpoint
      run: curl "http://localhost:5000/predict?school=MS&sex=F&age=18&address=U&famsize=GT3&Pstatus=T&Medu=1&Fedu=1&Mjob=other&Fjob=other&reason=course&guardian=mother&traveltime=2&studytime=2&failures=1&schoolsup=no&famsup=no&paid=no&activities=yes&nursery=yes&higher=yes&internet=no&romantic=no&famrel=1&freetime=1&goout=1&Dalc=1&Walc=1&health=5&absences=0"
    - name: G3 = 4 curl request to predict endpoint
      run: curl "http://localhost:5000/predict?school=GP&sex=F&age=17&address=U&famsize=GT3&Pstatus=T&Medu=4&Fedu=3&Mjob=other&Fjob=other&reason=reputation&guardian=mother&traveltime=1&studytime=2&failures=2&schoolsup=no&famsup=no&paid=yes&activities=no&nursery=yes&higher=yes&internet=yes&romantic=yes&famrel=3&freetime=4&goout=5&Dalc=2&Walc=4&health=1&absences=22"
            
