name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t ml:latest /dockerfile
    - name: Run a multi-line script
      run: docker run -d -p 5000:5000 ml
           curl http://localhost:5000/predict
